global using ChartViewer.Functions;
global using ScottPlot;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media;
global using System.ComponentModel;